version: '3'
services:
    filter:
        image: chgivan/filter:latest
        deploy:
            replicas: 5
            resources:
                limits:
                  cpus: '0.1'
                  memory: 20M
            restart_policy:
                condition: on-failure
        networks:
         - my_net
    rabbitmq:
        image: rabbitmq:3.6
        ports:
         - "4369:4369"
         - "5671:5671"
         - "5672:5672"
         - "25672:25672"
        networks:
         - my_net
networks:
    my_net:
